### ISSUE TITLE
Remove swears

### ISSUE THREAD

**Issue by protist** [necropolina/colordle#2]
**Is your feature request related to a problem? Please describe.**
Firstly, I love this variant and have been playing it daily. It's extremely original and an excellent implementation. However, I'd like to recommend it to my kids, and the gratuitous swearing makes me uncomfortable.

**Describe the solution you'd like**
I'd wonder if you'd mind removing the [swearing](https://github.com/necropolina/colordle/blob/main/src/constants/strings.ts#L3).

**Describe alternatives you've considered**
Erm... not recommending it, I guess?

**Additional context**
I don't really think it adds much to the game anyway. I don't think removing it would make the game worse.

**Comment by protist** [comment]
Thank you!

**Comment by necropolina** [comment]
No prob. After closing the issue I noticed deployment had initially failed, but the change should be live now. Thanks for the kind words, hope the kiddos enjoy the game!
